<script src="{{ asset('Userassets') }}/js/jquery.min.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery-migrate-3.0.1.min.js"></script>
<script src="{{ asset('Userassets') }}/js/popper.min.js"></script>
<script src="{{ asset('Userassets') }}/js/bootstrap.min.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.easing.1.3.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.waypoints.min.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.stellar.min.js"></script>
<script src="{{ asset('Userassets') }}/js/owl.carousel.min.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.magnific-popup.min.js"></script>
<script src="{{ asset('Userassets') }}/js/aos.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.animateNumber.min.js"></script>
<script src="{{ asset('Userassets') }}/js/bootstrap-datepicker.js"></script>
<script src="{{ asset('Userassets') }}/js/jquery.timepicker.min.js"></script>
<script src="{{ asset('Userassets') }}/js/scrollax.min.js"></script>
<script src="{{ asset('Userassets') }}/js/main.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.bundle.min.js"></script>